[Variables]
; Adv CPU IDs
CPUA-Sensor-ID=0xf0000501
CPUA-Sensor-Instance=0x0
; CPU Tctl/Tdie
CPUA-Tctl-Tdie=0x1000000
; CPU Core Voltage
CPUA-Core-Voltage=0x2000000
; CPU SoC Voltage
CPUA-SoC-Voltage=0x2000001
; CPU Core Current
CPUA-Core-Current=0x4000000
; CPU SoC Current
CPUA-SoC-Current=0x4000001
; CPU Package Power
CPUA-Package-Power=0x5000000
; CPU Core Power
CPUA-Core-0-Power=0x5000001
CPUA-Core-1-Power=0x5000002
CPUA-Core-2-Power=0x5000003
CPUA-Core-3-Power=0x5000004
CPUA-Core-4-Power=0x5000005
CPUA-Core-5-Power=0x5000006
; CPU Core Power
CPUA-Core-Power=0x5000007
; CPU SoC Power
CPUA-SoC-Power=0x5000008
; CPU Core+SoC Power
CPUA-Combined-Power=0x5000009